/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Futbolista;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2damb
 */
public class EntradaFutbolistas extends javax.swing.JFrame {

    Futbolista futbolista;

    /**
     * Creates new form EntradaFutbolistas
     */
    public EntradaFutbolistas() {
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoBottonGroup = new javax.swing.ButtonGroup();
        panelEntradaFutbolistas = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreFutbolistaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        apellidosFutbolistaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        naciionalidadFutbolista = new javax.swing.JTextField();
        edadFutbolistaLabel = new javax.swing.JLabel();
        edadSpinner = new javax.swing.JSpinner();
        alturaLabel = new javax.swing.JLabel();
        alturaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        masculinoRadioButton = new javax.swing.JRadioButton();
        femeninoRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        golesLabel = new javax.swing.JLabel();
        golesSpinner = new javax.swing.JSpinner();
        existenciaLabel = new javax.swing.JLabel();
        asistenciasSpinner = new javax.swing.JSpinner();
        tarjetasAmarillasCheckBox = new javax.swing.JCheckBox();
        panelAmarillasJPanel = new javax.swing.JPanel();
        cuantasAmarillasLabel = new javax.swing.JLabel();
        amarillasSpinner = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        cuantasRojasLabel = new javax.swing.JLabel();
        rojasSpinner = new javax.swing.JSpinner();
        enviarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();

        sexoBottonGroup.add(masculinoRadioButton);
        sexoBottonGroup.add(femeninoRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreLabel.setText("NOMBRE:");

        jLabel1.setText("APELLIDOS :");

        jLabel2.setText("NACIONALIDAD:");

        naciionalidadFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naciionalidadFutbolistaActionPerformed(evt);
            }
        });

        edadFutbolistaLabel.setText("EDAD:");

        alturaLabel.setText("ALTURA:");

        alturaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("CM");

        masculinoRadioButton.setText("MASCULINO");

        femeninoRadioButton.setText("FEMENINO");

        jLabel4.setText("SEXO");

        golesLabel.setText("GOLES:");

        existenciaLabel.setText("ASISTENCIAS:");

        tarjetasAmarillasCheckBox.setText("¿TE HAN SACADO TARJETAS AMARILLAS?");

        cuantasAmarillasLabel.setText("CUANTAS:");

        javax.swing.GroupLayout panelAmarillasJPanelLayout = new javax.swing.GroupLayout(panelAmarillasJPanel);
        panelAmarillasJPanel.setLayout(panelAmarillasJPanelLayout);
        panelAmarillasJPanelLayout.setHorizontalGroup(
            panelAmarillasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmarillasJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAmarillasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuantasAmarillasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amarillasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAmarillasJPanelLayout.setVerticalGroup(
            panelAmarillasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmarillasJPanelLayout.createSequentialGroup()
                .addComponent(cuantasAmarillasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amarillasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jCheckBox1.setText("¿TE HAN SACADO TARJETAS ROJAS?");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(246, 20));

        cuantasRojasLabel.setText("CUNATAS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuantasRojasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rojasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cuantasRojasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rojasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        enviarButton.setText("ENVIAR");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("CANCELAR");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        borrarButton.setText("BORRAR");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEntradaFutbolistasLayout = new javax.swing.GroupLayout(panelEntradaFutbolistas);
        panelEntradaFutbolistas.setLayout(panelEntradaFutbolistasLayout);
        panelEntradaFutbolistasLayout.setHorizontalGroup(
            panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaFutbolistasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaFutbolistasLayout.createSequentialGroup()
                        .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEntradaFutbolistasLayout.createSequentialGroup()
                                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edadFutbolistaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEntradaFutbolistasLayout.createSequentialGroup()
                                        .addComponent(golesLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(golesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nombreFutbolistaTextField)
                                        .addComponent(apellidosFutbolistaTextField)
                                        .addComponent(naciionalidadFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEntradaFutbolistasLayout.createSequentialGroup()
                                            .addComponent(existenciaLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(asistenciasSpinner))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEntradaFutbolistasLayout.createSequentialGroup()
                                            .addComponent(alturaLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(alturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel3)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEntradaFutbolistasLayout.createSequentialGroup()
                                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(panelAmarillasJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tarjetasAmarillasCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelEntradaFutbolistasLayout.createSequentialGroup()
                                .addComponent(borrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarButton)
                                .addGap(18, 18, 18)
                                .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(panelEntradaFutbolistasLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEntradaFutbolistasLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(masculinoRadioButton)))
                        .addGap(18, 18, 18)
                        .addComponent(femeninoRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelEntradaFutbolistasLayout.setVerticalGroup(
            panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaFutbolistasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(masculinoRadioButton)
                    .addComponent(femeninoRadioButton))
                .addGap(18, 18, 18)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreFutbolistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(apellidosFutbolistaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(naciionalidadFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadFutbolistaLabel)
                    .addComponent(edadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaLabel)
                    .addComponent(alturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(golesLabel)
                    .addComponent(golesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(existenciaLabel)
                    .addComponent(asistenciasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarjetasAmarillasCheckBox)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAmarillasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(panelEntradaFutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEntradaFutbolistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEntradaFutbolistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void naciionalidadFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naciionalidadFutbolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naciionalidadFutbolistaActionPerformed

    private void alturaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTextFieldActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed

        DefaultTableModel tabla = new DefaultTableModel();
        futbolista = new Futbolista();

       

    }//GEN-LAST:event_enviarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        
        sexoBottonGroup.clearSelection();
        
        
    }//GEN-LAST:event_borrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public JLabel getAlturaLabel() {
        return alturaLabel;
    }

    public void setAlturaLabel(JLabel alturaLabel) {
        this.alturaLabel = alturaLabel;
    }

    public JTextField getAlturaTextField() {
        return alturaTextField;
    }

    public void setAlturaTextField(JTextField alturaTextField) {
        this.alturaTextField = alturaTextField;
    }

    public JSpinner getAmarillasSpinner() {
        return amarillasSpinner;
    }

    public void setAmarillasSpinner(JSpinner amarillasSpinner) {
        this.amarillasSpinner = amarillasSpinner;
    }

    public JTextField getApellidosFutbolistaTextField() {
        return apellidosFutbolistaTextField;
    }

    public void setApellidosFutbolistaTextField(JTextField apellidosFutbolistaTextField) {
        this.apellidosFutbolistaTextField = apellidosFutbolistaTextField;
    }

    public JSpinner getAsistenciasSpinner() {
        return asistenciasSpinner;
    }

    public void setAsistenciasSpinner(JSpinner asistenciasSpinner) {
        this.asistenciasSpinner = asistenciasSpinner;
    }

    public JButton getBorrarButton() {
        return borrarButton;
    }

    public void setBorrarButton(JButton borrarButton) {
        this.borrarButton = borrarButton;
    }

    public JButton getCancelarButton() {
        return cancelarButton;
    }

    public void setCancelarButton(JButton cancelarButton) {
        this.cancelarButton = cancelarButton;
    }

    public JLabel getCuantasAmarillasLabel() {
        return cuantasAmarillasLabel;
    }

    public void setCuantasAmarillasLabel(JLabel cuantasAmarillasLabel) {
        this.cuantasAmarillasLabel = cuantasAmarillasLabel;
    }

    public JLabel getCuantasRojasLabel() {
        return cuantasRojasLabel;
    }

    public void setCuantasRojasLabel(JLabel cuantasRojasLabel) {
        this.cuantasRojasLabel = cuantasRojasLabel;
    }

    public JLabel getEdadFutbolistaLabel() {
        return edadFutbolistaLabel;
    }

    public void setEdadFutbolistaLabel(JLabel edadFutbolistaLabel) {
        this.edadFutbolistaLabel = edadFutbolistaLabel;
    }

    public JSpinner getEdadSpinner() {
        return edadSpinner;
    }

    public void setEdadSpinner(JSpinner edadSpinner) {
        this.edadSpinner = edadSpinner;
    }

    public JButton getEnviarButton() {
        return enviarButton;
    }

    public void setEnviarButton(JButton enviarButton) {
        this.enviarButton = enviarButton;
    }

    public JLabel getExistenciaLabel() {
        return existenciaLabel;
    }

    public void setExistenciaLabel(JLabel existenciaLabel) {
        this.existenciaLabel = existenciaLabel;
    }

    public JRadioButton getFemeninoRadioButton() {
        return femeninoRadioButton;
    }

    public void setFemeninoRadioButton(JRadioButton femeninoRadioButton) {
        this.femeninoRadioButton = femeninoRadioButton;
    }

    public JLabel getGolesLabel() {
        return golesLabel;
    }

    public void setGolesLabel(JLabel golesLabel) {
        this.golesLabel = golesLabel;
    }

    public JSpinner getGolesSpinner() {
        return golesSpinner;
    }

    public void setGolesSpinner(JSpinner golesSpinner) {
        this.golesSpinner = golesSpinner;
    }

    public JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public void setjCheckBox1(JCheckBox jCheckBox1) {
        this.jCheckBox1 = jCheckBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JRadioButton getMasculinoRadioButton() {
        return masculinoRadioButton;
    }

    public void setMasculinoRadioButton(JRadioButton masculinoRadioButton) {
        this.masculinoRadioButton = masculinoRadioButton;
    }

    public JTextField getNaciionalidadFutbolista() {
        return naciionalidadFutbolista;
    }

    public void setNaciionalidadFutbolista(JTextField naciionalidadFutbolista) {
        this.naciionalidadFutbolista = naciionalidadFutbolista;
    }

    public JTextField getNombreFutbolistaTextField() {
        return nombreFutbolistaTextField;
    }

    public void setNombreFutbolistaTextField(JTextField nombreFutbolistaTextField) {
        this.nombreFutbolistaTextField = nombreFutbolistaTextField;
    }

    public JLabel getNombreLabel() {
        return nombreLabel;
    }

    public void setNombreLabel(JLabel nombreLabel) {
        this.nombreLabel = nombreLabel;
    }

    public JPanel getPanelAmarillasJPanel() {
        return panelAmarillasJPanel;
    }

    public void setPanelAmarillasJPanel(JPanel panelAmarillasJPanel) {
        this.panelAmarillasJPanel = panelAmarillasJPanel;
    }

    public JPanel getPanelEntradaFutbolistas() {
        return panelEntradaFutbolistas;
    }

    public void setPanelEntradaFutbolistas(JPanel panelEntradaFutbolistas) {
        this.panelEntradaFutbolistas = panelEntradaFutbolistas;
    }

    public JSpinner getRojasSpinner() {
        return rojasSpinner;
    }

    public void setRojasSpinner(JSpinner rojasSpinner) {
        this.rojasSpinner = rojasSpinner;
    }

    public ButtonGroup getSexoBottonGroup() {
        return sexoBottonGroup;
    }

    public void setSexoBottonGroup(ButtonGroup sexoBottonGroup) {
        this.sexoBottonGroup = sexoBottonGroup;
    }

    public JCheckBox getTarjetasAmarillasCheckBox() {
        return tarjetasAmarillasCheckBox;
    }

    public void setTarjetasAmarillasCheckBox(JCheckBox tarjetasAmarillasCheckBox) {
        this.tarjetasAmarillasCheckBox = tarjetasAmarillasCheckBox;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alturaLabel;
    private javax.swing.JTextField alturaTextField;
    private javax.swing.JSpinner amarillasSpinner;
    private javax.swing.JTextField apellidosFutbolistaTextField;
    private javax.swing.JSpinner asistenciasSpinner;
    private javax.swing.JButton borrarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cuantasAmarillasLabel;
    private javax.swing.JLabel cuantasRojasLabel;
    private javax.swing.JLabel edadFutbolistaLabel;
    private javax.swing.JSpinner edadSpinner;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel existenciaLabel;
    private javax.swing.JRadioButton femeninoRadioButton;
    private javax.swing.JLabel golesLabel;
    private javax.swing.JSpinner golesSpinner;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton masculinoRadioButton;
    private javax.swing.JTextField naciionalidadFutbolista;
    private javax.swing.JTextField nombreFutbolistaTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JPanel panelAmarillasJPanel;
    private javax.swing.JPanel panelEntradaFutbolistas;
    private javax.swing.JSpinner rojasSpinner;
    private javax.swing.ButtonGroup sexoBottonGroup;
    private javax.swing.JCheckBox tarjetasAmarillasCheckBox;
    // End of variables declaration//GEN-END:variables
}
